name: asymmetric_2fa
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  encrypt: ^5.0.0
  pointycastle: ^3.1.2
  tuple: ^2.0.0

dev_dependencies:
  pedantic: ^1.10.0
